### ISSUE TITLE
Can't download pretrained models

### ISSUE THREAD

**Issue by GrumpyZhou** [lzx551402/ASLFeat#11]
Hi,

The download links for the pretrained models are not accessible to me. Can you double-check that? Thanks!

**Comment by lzx551402** [comment]
Yes, our AWS server is suffering some problem, I will let you know once it is resolved. Sorry for the inconvenience!

**Comment by lzx551402** [comment]
Hi, would you give another try? I think the service is now back online

**Comment by GrumpyZhou** [comment]
Yes now it works thanks!
