### ISSUE TITLE
Evaluation on Aachen day-and-night benchmark

### ISSUE THREAD

**Issue by jinyummiao** [lzx551402/ASLFeat#14]
Thanks for your remarkable works! I follow your instruction to evaluate the local feature on Aachen day-and-night benchmark by using [evaluation script](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/reconstruction_pipeline.py) mentioned. However, the results are much higher than ones provided in your paper (D2-Net, R2D2, SuperPoint, etc.) I have not fine-tuned the setup in the evaluation script and I cannot find the reason causing such gap. Could you give me some advice to reappear the correct results? Thanks :)

As a reference, my results are:
SuperPoint: 70.4/79.6/88.8
D2-Net: 74.5/85.7/99.0
R2D2: 74.5/84.7/98.0
which seems unreasonable ...

**Comment by zjhthu** [comment]
Aachen day-and-night dataset updated their `ground truth poses`, and all methods benefit from this ...

**Comment by jinyummiao** [comment]
Thanks for your reply but the improvement seems excessively large... Have you resubmitted the evaluation results to the benchmark recently?
