### ISSUE TITLE
Grayscale vs RGB input

### ISSUE THREAD

**Issue by uzpaka** [lzx551402/ASLFeat#4]
Hello,
Thank you for your work! 
I have noticed from your 'datasets/base_dataset.py' file that there are cases where your network accepts RGB inputs (if self.config['stage'] == 'reg'). However, when looking at all your evaluations, you are always feeding grayscale images to the network. I was wondering in which cases you would prefer RGB images, if any at all. In general, did you notice an increase in performance by using grayscale input instead of RGB?

Best,
Ali

**Comment by zjhthu** [comment]
Local features usually operate on grayscale images, e.g. SIFT. As said by Zixin, there is no significant difference between grayscale input and RGB.
