### ISSUE TITLE
FM-Bench features are symbolic links?

### ISSUE THREAD

**Issue by TLzh** [lzx551402/ASLFeat#7]
I extract FM-Bench features using `python evaluations.py --config configs/fmbench_eval.yaml`，but I find the kpts and descs are symbolic links. So When I run FM-Bench Pipline_Demo, the returned fid of `fopen('.keypoints')` is -1. And I get `Invalid file identifier. Use fopen to generate a valid file identifier.` 
There is the result when I run `file 0006*` in the features folder:
`0006_l.descriptors: symbolic link to /data_ssd/FM-Bench/Features_aslfeat_ms/TUM/0005_l.descriptors`
`0006_l.keypoints:   symbolic link to /data_ssd/FM-Bench/Features_aslfeat_ms/TUM/0005_l.keypoints`
`0006_r.descriptors: data`
`0006_r.keypoints:   data`

**Comment by sunshantong** [comment]
@TLzh Encountered the same problem as you. How did you solve it? Looking forward to your help. Thank you very much.
